#+BLOG: blog.datalab.es
#+CATEGORY: periodismodatos, datalab, taller
#+TAGS: datos, periodismodatos, laespañavacía, laponiadelsur
#+DESCRIPTION: Notas sobre el quinto taller de producción de periodismo de datos
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+TITLE: Madrid y los Objetivos de Desarrollo Sostenible, sexto taller de periodismo de datos.
#+DATE: <2018-01-13 sáb>
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil toc:nil

El *Taller de Periodismo de Datos* alcanza su sexta edición en 2018 y amplía su duración hasta las cinco
sesiones para desarrollar historias basadas en datos centradas en los [[http://www.undp.org/content/undp/es/home/sustainable-development-goals.html][Objetivos de Desarrollo Sostenible]] (*ODS*)
relacionados con la lucha contra el cambio climático en Madrid (ciudad, comunidad, región, área...).

#+CAPTION: ODS y Cambio Climático en Madrid
#+NAME: tpd18
#+ATTR_HTML: :alt Objetivos de Desarrollo Sostenible relacionados con la lucha contra el cambio climático :title tpd18 :width 480px
http://medialab-prado.es/mmedia/20/20866/500_0.png

* Introducción

La sexta edición del /taller de producción de periodismo de datos/ aprende de las ediciones anteriores, y en particular de la de 2017, para proponer un taller de cinco sesiones que viene cargada de cambios, con los cuales pretendemos mejorar tanto el desarrollo del taller como los proyectos que se realizan.

Trabajaremos sobre los *Objetivos de Desarrollo Sostenible* que tratan de la *lucha contra el cambio
climático* y cómo afecta a *Madrid* (ciudad, comunidad, región, área...).

** Contexto
En 2015 la ONU desarrolló 17 objetivos mundiales para erradicar la pobreza, combatir la desigualdad y la injusticia y solucionar el cambio climático. Si en 2016 trabajamos el tema de la desigualdad y la pobreza y en 2017 abordamos nuestro territorio con [[https://medialab-prado.github.io/tpd17][la España vacía]], en 2018 hacemos zoom sobre Madrid (y alrededores) y enfocamos nuestra lente sobre los ODS relacionados con el cambio climático.

* Desarrollo del taller

El Taller de Periodismo de Datos 2018 inicia su andadura el 8 de febrero, fecha de publicación de esta nota. Aquí anunciamos todos los detalles del taller.

En esta ocasión, al igual que en 2017, no os pedimos todavía una propuesta formal -aunque podéis registrarla
en cualquier momento en nuestro formulario-, sino que empecéis a trabajar en vuestra idea/propuesta/proyecto y
nos[[mailto:visualizar%20@%20medialab-prado%20.%20es][enviéis un correo]]/[[https://github.com/medialab-prado/tpd18/issues/new][creéis una issue]] para que lo añadamos a la lista de propuestas.

Os recomendamos alguna de estas plataformas para empezar a definir la propuesta: [[https://github.com/][GitHub]], [[http://gitlab.com/][GitLab]], [[https://bitbucket.org/][Bitbucket]], [[https://gogs.io][Gogs]], [[https://gitea.io/][Gitea]] o una solución similar que permita empezar a trabajar sobre la idea y aceptar la participación de otras personas. Nosotrxs, de momento, usamos [[https://github.com/medialab-prado/tpd18/][Github]], por lo que su uso nos permitirá cierta facilidad de integración.

#+BEGIN_NOTES
¿Por qué no os proponemos un Pad u otro sistema de documentación al vuelo en línea como Google Docs? Porque
todo lo que hagáis ahí no lo controláis de la misma manera. (de momento)
#+END_NOTES

** Plazo de presentación de proyectos

El plazo de presentación de proyectos finaliza diez días después del día de los datos abiertos, el *13 de
marzo*.

** Anuncio de proyectos seleccionados
El martes *20 de marzo* se anuncian los proyectos seleccionados 


** Herramientas de comunicación

Desde la tercera sesión hasta junio, cuando celebramos dos, los equipos harán un trabajo en línea o presencial.

Para lo primero es importante el haber conocido el conjunto de herramientas de comunicación que
nos pueden ayudar:
- Github
- Telegram, Whatsapp
- Correo electrónico
- Slack
- Otras

Para lo segundo, Medialab-Prado, siempre que su agenda lo permita, puede servir de espacio de reunión y trabajo.

* Sesiones

** Primera sesión: Software para el Periodismo de Datos

La *primera sesión* se desarrolla los días *13 y/o 14 de febrero*, la [[http://medialab-prado.es/article/ilovefs/][celebración del día del amor por el software libre]] -que ya [[http://medialab-prado.es/article/dia-del-amor-por-el-software-libre-ilovefs-2017][hemos organizado]] los dos años anteriores- pretendemos que toméis contacto con buena parte del software que nos va a acompañar durante el taller: [[https://git-scm.com/][git]], [[https://www.gnu.org/software/bash/][bash]], [[https://www.gnu.org/][GNU/Linux]], edición de texto, HTML, Web, edición gráfica, visualización, mapas, Python, R... Cada uno de los proyectos puede aprovechar lo que mejor
desee de estas tecnologías.

Más información en [[http://medialab-prado.es/article/ilovefs18][ILOVEFS18]].

** Segunda sesión: Datos (abiertos) para el Periodismo de Datos

La *segunda sesión* coincide con la celebración del [[http://madrid.opendataday.org][día de los datos abiertos]], *viernes 2 y sábado 3 de marzo*. Si en la primera sesión aprendemos de software, en la segunda de datos: cómo hacer peticiones, portales de datos, cómo recopilar datos, datos enlazados, Wikipedia como fuente de datos, scraping... Los proyectos se presentarán previamente y se podrá trabajar en la búsqueda de datos para los mismos.

Más información en [[http://medialab-prado.es/article/odd18][Open Data Day]]

** Tercera sesión: Jornadas de Periodismo de Datos 2018, simposio sobre el /efecto Airbnb/ en Madrid y presentación de proyectos y colaboradorxs del taller

La *tercera sesión* se compone a su vez de tres eventos en sí, *del 17 al 22 de abril*:

- *Jornadas de Periodismo de Datos* *JPD18*, del 17 al 19 de abril. Al igual que en 2017, aprovechamos la convocatoria del taller para aprender, compartir o difundir proyectos de periodismo de datos y sirve como simposio previo a la sesión del TPD18.

- *Taller sobre el efecto Airbnb en Madrid*. Una de las actividades de las Jornadas será este encuentro de iniciativas tecnopolíticas que están abordando el tema y espacio idóneo para poner en práctica conocimientos de software libre sobre una temática relacionada con el TPD18.

- Tercera sesión del taller: se presentan los *proyectos seleccionados*, se presentan lxs *colaboradorxs* y se crean formalmente los *equipos* para empezar -o continuar- trabajando.

** Cuarta sesión: ¡a tope!

La cuarta sesión es *del 8 al 10 de junio*, donde los equipos trabajan en el desarrollo de su proyecto con el apoyo de lxs mentorxs técnicxs y periodistas de datos.

** Quinta sesión: presentación final

La quinta y última sesión, *del 22 al 24 de junio*, sirve para terminar el proyecto y presentarlo públicamente.

* Resumen de fechas:

- 8 de febrero, [[http://s.coop/tpd18][anuncio del taller]] y publicación de la [[http://medialab-prado.es/article/tpd18cfp][convocatoria de proyectos]].
- 13-14 febrero, *primera sesión*: software para periodismo de datos durante [[http://medialab-prado.es/article/ilovefs18][ILOVEFS18]].
- 2-3 marzo, *segunda sesión*, busca datos durante [[http://medialab-prado.es/article/odd18][OpenDataDay 2018]], día de los datos abiertos.
- 12 marzo, fecha límite de presentación de propuestas.
- 26 marzo, anuncio de proyectos seleccionados y publicación de convocatoria de colaboradoras.
- 17-19 abril, *Jornadas de Periodismo de Datos*
- 17-19 abril, *simposio sobre el efecto Airbnb en Madrid*.
- 20-22 abril, *tercera sesión*: presentación de proyectos y colaboradorxs, formación de equipos.
- 8-10 junio, *cuarta sesión*: trabajo.
- 22-24 junio, *quinta y última sesión*, presentación de proyectos.

* Por qué los *Objetivos de Desarrollo Sostenible*
Los objetivos de desarrollo sostenible ofrecen un marco de referencia y un marco de actuación compartida. Son
una convocatoria mundial para acabar con la pobreza, conseguir la paz y la prosperidad de la humanidad.

Son [[http://www.undp.org/content/undp/en/home/sustainable-development-goals.html][17 objetivos]] construidos sobre la base de los [[http://www.undp.org/content/undp/en/home/sustainable-development-goals/background.html][objetivos de desarrollo del milenio]] pero que introducen acciones contra el cambio climático, la desigualdad económica, la innovación y el consumo sostenible, la paz y la justicia, entre otras prioridades. Los objetivos se interconectan y a menudo la clave para conseguir uno de ellos involucra a otros.

Si en 2016 trabajamos el tema de la desigualdad y la pobreza a propósito de la elaboración del [[https://decide.madrid.es/derechos-humanos/plan][Plan de Derechos Humanos del Ayuntamiento de Madrid]] y en 2017 investigamos el territorio nacional a través de [[https://medialab-prado.github.io/tpd17][la España vacía]], en 2018 volvemos a poner el foco sobre Madrid (y alrededores) y centramos nuestra lente sobre los ODS relacionados con el cambio climático.


* Proyectos inspiradores

Si conoces alguno, propónlo a través de una issue.

- [[https://www.eventbrite.com/e/open-bike-data-mapping-with-openstreetmap-registration-34806438996#][Open Bike Data & Mapping with OpenStreetMap]]
- [[http://2017.summerofcode.be/][Open Summer of Code]]
- [[http://datapiloten.be/parking/][Linked Open Data Parking]]
- [[http://tripscore.eu/][TripScore]]
- [[http://cyclenetworks.osm.be/brumob/#map=12/50.84072/4.36657][Cycle Network Tools]]
- [[https://cyclabilite.droitauvelo.org/][Ciclabilite]]
- [[https://osoc17.github.io/lopeningent_backend/][Lopen In Gent]]

* Datos sobre ODS

** España
- [[http://ine.es/dyngs/INEbase/es/categoria.htm?c=Estadistica_P&cid=1254734710990][Datos demográficos, Instituto Nacional de Estadística (INE)]]
- [[http://centrodedescargas.cnig.es/CentroDescargas/catalogo.do;jsessionid=CD432E0A4150A63D3B8262B8329B748B#selectedSerie][Centro de descargas, Centro Nacional de Información Geográfica (CNIG)]]
- [[http://www.ign.es/ign/layoutIn/sismoFormularioCatalogo.do][Instituto Geográfico Nacional, IGN]]
- [[http://www.mapama.gob.es/es/cartografia-y-sig/ide/][Catálogo de datos, MAPAMA]]
- [[https://sede.minetur.gob.es/es-ES/datosabiertos/catalogo-datos/Paginas/catalogo.aspx?tm=9][Catálogo de datos, Ministerio de Industria]]
- [[http://www.minhafp.gob.es/es-ES/GobiernoAbierto/Datos%20Abiertos/Paginas/Catalogodedatosabiertos.aspx][Catálogo de datos, Ministerio de hacienda]]
- [[http://www.msssi.gob.es/estadEstudios/estadisticas/sisInfSanSNS/home.htm][Catálogo de datos, Ministerio de Sanidad, Servicios sociales e Igualdad]]
- [[https://www1.sedecatastro.gob.es/OVCFrames.aspx?TIPO=consulta][Datos catastrales, sede electrónica del catastro]]
- [[http://www.aemet.es/es/portada][Agencia Estatal de Meteorología (AEMET)]]
- [[http://www.mapama.gob.es/es/cartografia-y-sig/][Cartografía y SIG, MAPAMA]]
- [[http://www.mapama.gob.es/es/cartografia-y-sig/ide/descargas/default.aspx][Datos geográficos, MAPAMA]]
- [[http://www.mapama.gob.es/es/estadistica/temas/][Estadísticas, MAPAMA]]
- [[http://www.mapama.gob.es/es/cartografia-y-sig/ide/][Infraestructura de Datos Espaciales, MAPAMA]]
- [[http://www.mapama.gob.es/es/cartografia-y-sig/ide/descargas/costas-medio-marino/guia-playas-descargas.aspx][Base de datos de playas en España, MAPAMA]]
- [[https://www.csn.es/ciemat-pimic/datos-generales][Consejo de Seguridad Nuclear]]


** Europa
- [[http://ec.europa.eu/eurostat/data/database][EUROSTAT. Catálogo de datos]]
- [[http://urban.jrc.ec.europa.eu/][Comisión Europea. Plataforma de datos urbanos]]
- [[http://ec.europa.eu/eurostat/statistics-explained/index.php/Tourism_statistics_at_regional_level][Estadísticas de turismo - Eurostat]]
- [[http://ec.europa.eu/eurostat/statistics-explained/index.php/SDG_-_Introduction][Estadísticas de ODS en Eurostat]]

** Internacional
- [[http://data.un.org/][Naciones Unidas. Catálogo de datos]]
- [[http://datos.bancomundial.org/indicador][Banco Mundial. Catálogo de datos]]
- [[http://www.who.int/gho/en/][Organización Mundial de la Salud. Catálogo de datos]]
- [[http://www.sdgdatalabs.org/data/][SDG Labs]]
- [[http://www.undatarevolution.org/report/][UN Data Revolution]]
- [[http://blogs.worldbank.org/ic4d/sustainable-development-goals-and-open-data][SDG and Open Data]]
- [[https://www.globalpolicywatch.org/blog/2015/11/23/sdg-indicators-and-data/][SDG and Data]]
- [[https://sdgactioncampaign.org/tag/data/][SDG Action Campaign]]
- [[https://sdgactioncampaign.org/tag/data-for-development/][SDG Action Campaign - data for development]]
- [[http://sdgactioncampaign.org/][Festival of Global Action]]
- [[https://sustainabledevelopment.un.org/globalsdreport/2019#call][Global Sustainable Development Report 2019]]
- [[http://act4sdgs.org/][Act 4 SDGs]]
- [[http://action4sd.org/][Action for SD]] 
- [[http://data.myworld2030.org/][Data MYWorld 2030]]
- [[https://openknowledge.worldbank.org/bitstream/handle/10986/28542/120500.pdf?sequence=5][Global Mobility Report 2017]]
- [[http://www.sum4all.org/][Sustainable Mobility for All]]
- [[http://www.sum4all.org/data/files/data-import/country-snapshots/Spain.pdf][Sustainable Mobility for All, Spain]]
- [[http://www.undp.org/content/undp/en/home/sustainable-development-goals/resources.html][Recursos de Naciones Unidas]]
- [[http://data.un.org/][Naciones Unidas. Catálogo de datos]]
- [[http://datos.bancomundial.org/indicador][Banco Mundial. Catálogo de datos]]
- [[http://www.who.int/gho/en/][Organización Mundial de la Salud. Catálogo de datos]]
* Equipo
Organiza el Laboratorio de Datos de Medialab-Prado.

Participan: (/en construcción/)
** Coordinación
- [[http://medialab-prado.es/person/adolfoanton][Adolfo Antón Bravo]], responsable del DataLab Madrid y coordinador del taller.
- [[http://medialab-prado.es/person/sara-calvo-tarancon][Sara Calvo Tarancón]], periodista.
- [[http://medialab-prado.es/person/julian-perez][Julián Pérez]], artista digital, ex-mediador Medialab Prado y miembro de AVFLOSS.
** Mentorxs técnicxs
- [[http://medialab-prado.es/person/alejandrozappala][Alejandro Zappala]], ingeniero en cartografía y geodesia, [[http://www.adappgeo.net][investigador]]
- [[http://jesusda.com][Jesús David Navarro]], diseñador gráfico y web con Software Libre.
- [[http://medialab-prado.es/person/carlosjgilbellosta][Carlos Gil Bellosta]], científico de datos y apasionado de R.
** Relatoría
- [[http://sandrasm.com][Sandra Sánchez Merinero]], periodista de datos en Xataka.
- [[http://sihayperosquevalgan.com][María Navarro]], periodista de en #LaCafetera (Radio Cable)
** Mediación
- Mertxe Bilbao, relaciones públicas.
** Mentorías de periodismo y visualización de datos
/En construcción/:
- Adrián Blanco (El Confidencial)
- María Zuil (El Confidencial)
- Idoia Sota (El País)
- Verónica Ramírez (La Sexta)
- /Más por venir/...
