#+TITLE: Propuesta para el Taller de Periodismo de Datos 2018


* Propuesta de proyecto
Madrid, exportadora de fosfatos


* Datos del solicitante

- Nombre: Juana
- Apellidos: Sinmiedo
- Nacionalidad (opcional): Española
- Número de DNI o pasaporte (opcional):
- Ciudad: Madrid
- País: España
- Teléfono: 600 NN NN NN
- Correo electrónico: prueba@noexiste.es
- Página web (opcional): https://juanasinmiedo.github.io

* Título del proyecto 

Madrid, exportadora de fosfatos

* Resumen del proyecto

Al igual que con el petróleo, dicen que se ha alcanzado el pico de los fosfatos. Sin embargo, en nuestra ciudad tenemos una mina: las depuradoras están generando más fosfatos que muchos lugares tradicionales.

¿Cómo ha evolucionado el mercado? ¿Puede generar un nicho de empleo? ¿Se puede repartir esa riqueza? ¿Es un ejemplo de economía circular? ¿Qué zonas aportan más? ¿Dónde se emplean esos fosfatos? ¿Llegan de vuelta a nosotrxs en forma de verduras y hortalizas?

* Descripción del proyecto 

El proyecto pretende detectar singularidades en el cambio de modelos productivos a nivel municipal. Para conseguir las variables necesarias, la investigación de los datos se articula en torno a tres ejes de fuentes de datos ya localizadas y recopiladas:

** Demográfico

Datos.madrid.es, Catastro e INE disponen de datos de población a nivel municipal desglosados en varios conceptos (edad, nivel de estudios...). El análisis de la población nos dará pistas sobre los municipios que más envejecen, los que pierden población y los que están a punto de desaparecer.

** Socioeconómico
Datos.madrid.es, Comunidad de Madrid, Ministerio de Hacienda

** Laboral/Empresarial
Nuevas empresas, autónomos, organizaciones empresariales, sindicatos, Registro Mercantil (BORME)

* Formato

Queremos hacer una web cuya arquitectura de la información debe cumplir los requisitos del diseño centrado en la experiencia de usuarix. Los gráficos y visualizaciones siempre deben servir para aportar valor a la historia y no simplemente para mostrar el contenido de los datos.

Los gráficos se utilizarán para permitir explorar datos especialmente significativos, pero lo que se pretende es que la capa de análisis de datos no sea el objetivo sino el medio para encontrar casos específicos, historias singulares.

Por ello también trabajaremos con trabajo de campo al uso: contrastar los datos con distintas fuentes, entrevistar a testigxs y a expertxs, extraer las cifras más importantes y utilizar las conclusiones para vertebrar un relato periodístico.

* Requisitos

Todos los miembros del grupo de trabajo deben tener ordenador portátil y han de saber usarlo. Da igual el sistema operativo pero han de conocer aplicaciones libres.

Para las entrevistas y los recursos se recomienda mucho ánimo, grabadora, cámara fotográfica, móvil...

** Perfiles

Descripción del perfil de los colaboradores que requiere el proyecto

1. Análisis de datos y creación de contenido: cualquier persona interesada en en análisis de datos para crear una historia periodística. Hojas de cálculo, Refine, R, Python, Bash, SQL, etc.
2. Redacción y recopilación de datos de campo:  dos o tres perfiles de periodista.
3. Diseño gráfico: conocimiento de aplicaciones libres relacionadas con diseño gráfico.
4. Cartografía, mapas: personas con conocimientos en sistemas de información geográfica.
5. Web: conocimiento de estándares web, desarrollo web, entornos libres, Bootstrap, SASS...

** Otros requisitos con estimación de presupuesto

No hay requisitos adicionales

* Calendario de producción

** Lanzamiento
Anuncio del proyecto el 13 febrero
** Recopilación de datos
Presentación de nuevo durante el día de los datos abiertos, trabajo de recopilación de datos.
** Prueba de concepto
Durante la tercera sesión
** Recopilación de materiales
Durante el mes de mayo
** Web
Durante la quinta sesión
** Presentación
En la sesión final

* Curriculum Vitae
(opcional)

* Motivaciones y expectativas
(opcional)

* Conocimientos técnicos
(opcional)

* Sistemas operativos

Uso básico de sistemas operativos GNU/Linux.

* Equipo propio

¿Dispones de ordenador portátil?

Sí, claro, con sistema operativo GNU/Linux.
